// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHlYRTCluSl5YQw6ddwMIpXDuH_C3NoI',
    appId: '1:571617047062:web:b7c9468ade033d614e3b37',
    messagingSenderId: '571617047062',
    projectId: 'stu-app-ced87',
    authDomain: 'stu-app-ced87.firebaseapp.com',
    storageBucket: 'stu-app-ced87.firebasestorage.app',
    measurementId: 'G-SCNQD94H9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxB08vHBHv3fj10thj_pJ3TiT90w0Kjqg',
    appId: '1:571617047062:android:5e23f828238c536e4e3b37',
    messagingSenderId: '571617047062',
    projectId: 'stu-app-ced87',
    storageBucket: 'stu-app-ced87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-qU1iB4flOycdoURZV99K6rR1IS-zoxs',
    appId: '1:571617047062:ios:6014f53410bf73ba4e3b37',
    messagingSenderId: '571617047062',
    projectId: 'stu-app-ced87',
    storageBucket: 'stu-app-ced87.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppUtSt',
  );
}
